### ISSUE TITLE
Database Issue

### ISSUE THREAD

**Issue by rzr1994** [switch-model/switch-china-open-model#1]
Hello, I would like to know if the switch-china database is missing some data? When I run it, I get the following error:
ERROR: Constructing component 'BuildStorageEnergy_assign_default_value' from
    data=None failed:
        ValueError: For storage generator g='West_Inner_Mongolia-Hydro_Pumped-
        ep-35001', gen_build_predetermined[g, 2010] has been specified, but
        not gen_build_energy_predetermined[g, 2010] or
        gen_storage_energy_to_power_ratio[g].

**Comment by zhangzhang519** [comment]
Sorry to bother, but I’m encountering the same issue. I’ve tried adding more data and even removing the problematic generator, but the error still persists. Could you please share how you resolved it? Any suggestions or advice on a solution would be greatly appreciated. Looking forward to your response, and thank you very much in advance!
